export const CLIENT_REQUEST = "CLIENT_REQUEST";
export const CLIENT_FAIL = "CLIENT_FAIL";
export const CLIENT_LIST_SUCCESS = "CLIENT_LIST_SUCCESS";
export const CLIENT_CREATE_SUCCESS = "CLIENT_CREATE_SUCCESS";
export const CLIENT_UPDATE_SUCCESS = "CLIENT_UPDATE_SUCCESS";
export const CLIENT_DELETE_SUCCESS = "CLIENT_DELETE_SUCCESS";