export const INVOICE_LIST_SUCCESS = "INVOICE_LIST_SUCCESS";
export const INVOICE_CREATE_SUCCESS = "INVOICE_CREATE_REQUEST";
export const INVOICE_GET_SUCCESS = "INVOICE_GET_SUCCESS";
export const INVOICE_DELETE_SUCCESS = "INVOICe_DELETE_SUCCESS";
export const INVOICE_UPDATE_SUCCESS = "INVOICE_UPDATE_SUCCESS";
export const START_LOADING = "START_LOADING";
export const INVOICE_FAIL = "INVOICE_FAIL";
